name: LeetCode Daily Email

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib requests

      - name: Run LeetCode sender
        env:
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
        run: python send_email.py
